### ISSUE TITLE
是我的配置有问题？

### ISSUE THREAD

**Issue by yy007668** [silenceshell/docker_mirror#2]
[root@localhost docker]# python docker_mirror.py
Traceback (most recent call last):
  File "docker_mirror.py", line 153, in <module>
    speed = get_speed(k, v)
  File "docker_mirror.py", line 123, in get_speed
    version = client.version()[u'Version']
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 186, in version
    return self.api.version(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/daemon.py", line 179, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 194, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

**Comment by silenceshell** [comment]
docker进程是不是没开？
试试 docker version 命令，能不能看到Server的版本
