### ISSUE TITLE
client is newer than server 

### ISSUE THREAD

**Issue by wangshun1121** [silenceshell/docker_mirror#3]
Traceback (most recent call last):
  File "./docker_mirror.py", line 153, in <module>
    speed = get_speed(k, v)
  File "./docker_mirror.py", line 123, in get_speed
    version = client.version()[u'Version']
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 186, in version
    return self.api.version(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 179, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 231, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 227, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)

- [x] docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.21)")

**Comment by wangshun1121** [comment]
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
