### ISSUE TITLE
Failed to execute docker_mirror.py in centOS7.6

### ISSUE THREAD

**Issue by JohnGuoy** [silenceshell/docker_mirror#7]
Traceback (most recent call last):
  File "./docker_mirror.py", line 166, in <module>
    cost_time = get_speed(k, v)
  File "./docker_mirror.py", line 133, in get_speed
    set_docker_config_ce(mirror_url)
  File "./docker_mirror.py", line 111, in set_docker_config_ce
    docker_config = get_config_ce(dist)
  File "./docker_mirror.py", line 59, in get_config_ce
    return docker_ce_config_map[dist]["config"]
KeyError: 'CentOS Linux'

**Comment by kimpengjiang** [comment]
I think the problem lies in the dictionary key value of "CentOS Linux". The key value of the dictionary in python is preferably without spaces. I hope I can help you.

**Comment by silenceshell** [comment]
fix in #8
